# -*- coding: utf-8 -*-
"""CarPredictionproject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ywVfOfXodMyejCMI550OYFVRl4_AfiYW
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import Lasso
from sklearn.linear_model import LinearRegression
from sklearn.metrics import  r2_score,mean_squared_error,mean_absolute_error
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

car = pd.read_csv("/content/car data.csv")
car.head(5)

car.tail(10)

car.info()

car.shape

car.describe()

print((car).Fuel_Type.value_counts())
print((car).Seller_Type.value_counts())
print((car).Transmission.value_counts())

le = LabelEncoder()
car['Fuel_Type'] = le.fit_transform(car['Fuel_Type'])
car['Seller_Type'] = le.fit_transform(car['Seller_Type'])
car['Transmission'] = le.fit_transform(car['Transmission'])



car.tail(10)

X = car.drop((["Selling_Price","Car_Name"]),axis=1)
y = car["Selling_Price"]
print(X)
print(y)

X_train , X_test , y_train , y_test = train_test_split(X,y,test_size=0.1,random_state=2)
print(X_train)
print(X_test)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
print(X_train_scaled)
print(X_test_scaled)

model = LinearRegression()
model.fit(X_train_scaled,y_train)

y_pred = model.predict(X_test_scaled)

plt.scatter(y_test,y_pred)
plt.xlabel("Actual Prices")
plt.ylabel("Predicted Prices")
plt.title("Actual Prices vs Predicted Prices")
plt.show()

r2_score = r2_score(y_test,y_pred)
print(r2_score)

